### ISSUE TITLE
Go-live checklist

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#39]
This is the series of events that has to happen to switch from http://docs.strongloop.com to http://loopback.io/doc:
- [x] Review and test all migrated English content.
- [x] Fix all broken links per #44 
- [x] Fix search feature per #31.
- [x] Incorporate README content from example repos, etc. per #30.
- [x] Import translated docs from Confluence per #37.
- [x] Fix tags per #41 (not required, but "nice to have")
- [x] Set up Google Analytics per #45.
- [x] Copy LB 2.x content into LB3 directory and make other initial changes in 3.0 docs.
- [x] Add link in header nav bar on loopback.io to http://loopback.io/doc.
- [x] Publish blog post announcing new doc site, deprecating old site, explaining how to contribute, etc.
- [x] Add redirects on docs.strongloop.com to corresponding pages in http://loopback.io/doc and deprecation notices everywhere else.
- [x] Update links to docs on strongloop.com (Dave W), https://developer.ibm.com/open/, KC docs, and anywhere else.

**Comment by crandmck** [comment]
Redirects task covered by #114
