### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by crandmck** [loopbackio/loopback.io#429]
This is the epic issue to track work on redesigning the loopback.io website.  In general, the time-frame for the redesign should align with the production/GA release of loopback-next (v4).

- [ ] Mock-ups - "overview" pages (#430), "doc" pages (http://loopback.io/doc/) #432
  - [ ] Mobile view
  - [ ] Desktop view
- [ ] Implementation - "overview" pages (#430), "doc" pages (http://loopback.io/doc/) #432
  - [ ] Mobile view
  - [ ] Desktop view
- [ ] Move API docs from strongloop.com to loopback.io domain.  #133 
- [ ] New sidebar on doc pages should address #425 
- [ ] Discuss whether to change LoopBack logo and how. #431

**Comment by DaveYVR** [comment]
(edited by @crandmck)
I created a new issue specifically for the logo discussion/work: #431. 
@DaveYVR I moved this comment into that issue.

**Comment by crandmck** [comment]
Yeah, perhaps just change from green to blue color scheme, rather than a complete redesign?

**Comment by hacksparrow** [comment]
Let's keep the logo change consideration towards the end.

@crandmck I have formatted the list a little differently to modularize the tasks.

**Comment by crandmck** [comment]
OK, thanks @hacksparrow I created a couple new issues to cover the rest of the tasks.  We can further break them down if needed.  I agree logo discussion can come later.

**Comment by dhmlau** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/issues/817.
We got the design team created the blueprint for us.
